### ISSUE TITLE
Python works, App does not

### ISSUE THREAD

**Issue by jappyjan** [mdbraber/radiobar#3]
When compiled to a ".app" file the app does not start. Instead i get an error message "RadioBar Error" with the options "Open Console" and "Terminate".
Clicking on "Open Console" opens the system Error Console, but does not offer any help...

**Comment by mdbraber** [comment]
Did you try starting the Application binary separately in a Terminal? It's `/Applications/RadioBar.app/Contents/MacOS/RadioBar` if you installed it under Applications. What does that give you in the Terminal?

**Comment by the-leonat** [comment]
i could link this to a an error in formatting of the `channels.json` file. remember: the last element in a list should **not** have a trailing comma: 

```
{
  list: [
    element,
    element // <-- no comma
 ]
}
